DECLARE
  AVERAGEVAL NUMBER;
BEGIN

  AVGRAGEPRICE(
    AVERAGEVAL => AVERAGEVAL
  );
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('AVERAGEVAL = ' || AVERAGEVAL);
*/ 
  :AVERAGEVAL := AVERAGEVAL;
--rollback; 
END;
