DECLARE
  MYBOOKID NUMBER;
  MYBOOKNAMNE VARCHAR2(200);
  MYPUBLISHER VARCHAR2(200);
  MYPRICE NUMBER;
BEGIN
  MYBOOKID := NULL;
  MYBOOKNAMNE := NULL;
  MYPUBLISHER := NULL;
  MYPRICE := NULL;

  INSERTBOOK(
    MYBOOKID => MYBOOKID,
    MYBOOKNAMNE => MYBOOKNAMNE,
    MYPUBLISHER => MYPUBLISHER,
    MYPRICE => MYPRICE
  );
--rollback; 
END;
