DECLARE
  MYBOOKID NUMBER;
  MYBOOKNAME VARCHAR2(200);
  MYPUBLICSHER VARCHAR2(200);
  MYPRICE NUMBER;
BEGIN
  MYBOOKID := NULL;
  MYBOOKNAME := NULL;
  MYPUBLICSHER := NULL;
  MYPRICE := NULL;

  INSERTORUPDATE(
    MYBOOKID => MYBOOKID,
    MYBOOKNAME => MYBOOKNAME,
    MYPUBLICSHER => MYPUBLICSHER,
    MYPRICE => MYPRICE
  );
--rollback; 
END;
